### ISSUE TITLE
Drop Shop PlugIn Creates 2nd Buy Now Button on WooCommerce Products with Attributes

### ISSUE THREAD

**Issue by incartmarketing** [roykho/woocommerce-drop-shop#2]
Drop Shop PlugIn Creates 2nd Buy Now (non-functioning) Button on WooCommerce Products with Attributes. Please see porterandyork.com for an example. Try dropping a steak product in the cart. They all have selections to choose from (weight of meat). There is a big button that doesn't work. WooThemes says it's your plug-in doing it. Please advise. Thanks.

**Comment by roykho** [comment]
No, you're using Splashing Pixels plugin.  That plugin is no longer maintained.  I suggest you don't use it.
