### ISSUE TITLE
Plugin is activated and not seeing anything?

### ISSUE THREAD

**Issue by kmcaloon** [roykho/woocommerce-drop-shop#4]
Hey, interested in trying this out but can't seem to get it to do anything. I have activated it but am not finding it under product settings. I've tried it with twentysixteen and still nothing. Any clue?

**Comment by roykho** [comment]
Hello, so in the future please post any support related questions here https://wordpress.org/support/plugin/woocommerce-drop-shop

Meanwhile, by default the cart will show up in the footer and only on shop pages.  And did you make sure you actually have WooCommerce plugin installed and activated?
