### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by xellardoor** [roykho/woocommerce-drop-shop#5]
Hello Roy,

What an awesome plug-in you have built!
Drop Shop plug-in is just the one I was looking for and it works great in desktop.
However, it would be really awesome if I could also use it in mobile version.

When I tried it in mobile, I could not drag items to the cart, using my finger to drag,
so I tried it with chrome browser by shrinking the browser to fit mobile size and I found when I drag two or more items in the cart,  total price, view cart, and check out button disappears.

Plus, if I click an item in the cart to see the product detail and hit back, there is nothing in the Drop Shop cart, but as I drop another item in the cart, items that were previously added appears.

If you could kindly fix these, it would be super awesome, but I realize that you have many projects, so if you would not mind, I would be more than happy to purchase your plug-in or pay for such customization.

Again, thank you so much for such a great plug-in and I hope you keep rocking with awesome plug-ins and projects :)

Cheers,

Hyo

**Comment by roykho** [comment]
Hello, yes full mobile compatibility has always been on my mind however my full time job is preventing me from having any spare moment to update this.  But I will get to it soon.
