### ISSUE TITLE
Integration with Woocommerce Photography?

### ISSUE THREAD

**Issue by s7media** [roykho/woocommerce-drop-shop#6]
Hi there, great plugin. Is it possible to get this to work with Woocommerce Photography? That plugin uses it's own product type called Photograph. You can drag images to the drop bar, but the cog spins forever, and the error Uncaught SyntaxError: Unexpected end of JSON input occurs.

Thanks

**Comment by roykho** [comment]
Hello. While I don't plan on specifically making the two compatible, I can think about adding ways for you to manipulate it yourself such as hooks into the product type and JS triggers.

**Comment by roykho** [comment]
ref #8
